### ISSUE TITLE
Content upload to the room are not saved across sessions

### ISSUE THREAD

**Issue by thitsa** [BinauralMeet/binaural-meet#107]
I noticed that recently we no longer save content I uploaded to a room from a previous session. I remember that before if I use the same room name it will reload the content from the previous session. Is this the new intended behavior? How long do we keep files on the content server?

**Comment by hasevr** [comment]
This is intended behavior.
When all participants leave, the relay server removes contents except wallpapers.
Also, when the relay server is restarted, nothing remains. So, please save the contents locally. I'm considering backing up contents on the relay server's disk.

**Comment by thitsa** [comment]
What would be the best way to implement a feature to save content across sessions? Another content server? Files on local drive?

**Comment by hasevr** [comment]
If you set content as wallpaper it will keep in memory even when all participants leave the room. But still not saved to file and when restart server, the contents gone.
