### ISSUE TITLE
Getting the name of the room from the URL

### ISSUE THREAD

**Issue by thitsa** [BinauralMeet/binaural-meet#108]
In Jitsi, the last name in the path URL is taken as the room name. Also any room name you enter into the dialog box is added to the URL to make it easy to copy the URL of the room.

e.g.
http://acme.com/foo/bar
"bar" is taken as the name of the room

In Binaural, it will take "foo/bar" and convert it to "foo_bar". Is there a reason room names are handled differently in Binaural?

**Comment by hasevr** [comment]
In jitsi or xmpp some characters have special meanings. / also. Please try https://meet.jit.si/abc/def/hij .
In, BM I just convert such characters into _ . Also capital characters can not be used.

**Comment by mumtazalam86** [comment]
I am getting this error in the latest source
"TypeScript error in D:/Work/binaural-meet/src/components/leftBar/StatusDialog.tsx(96,56):
Property 'connectionQuality' does not exist on type 'JitsiConference'.  TS2339"

Can you help me what could be the reason and how to resolve this.

**Comment by hasevr** [comment]
@mumtazalam86 Please ask via Discord https://discord.com/invite/xEbz7XKguB
