### ISSUE TITLE
Issue in configuring

### ISSUE THREAD

**Issue by mumtazalam86** [BinauralMeet/binaural-meet#110]
I am getting this error in the latest source
"TypeScript error in D:/Work/binaural-meet/src/components/leftBar/StatusDialog.tsx(96,56):
Property 'connectionQuality' does not exist on type 'JitsiConference'. TS2339"

Can you help me what could be the reason and how to resolve this.

**Comment by hasevr** [comment]
I don't have this issue. Please give me yarn.lock file.
