### ISSUE TITLE
Video preview and presenter's video <- Auto toggle video stream

### ISSUE THREAD

**Issue by mumtazalam86** [BinauralMeet/binaural-meet#112]
I am trying to auto toggle the video stream based on the user clicks on video Icon. Currently when a user clicks on the video icon from the main menu then that user's video start streaming on its Icon. But what I am trying to achieve is,
   - When user clicks on video icon then its video start streaming on a singular video control on the canvas screen and close all the remote users video stream and toggle off their video icon and they start viewing my video Stream. In the same way if any remote user who is viewing my stream and if they click on their video icon then my stream stops and toggle off my video icon and start their video stream and rest users start viewing that user's stream instead of mine. That means at a time only one user can share the stream and rest streams should be off.
   
  OR
- When you press the VIDEO button on the main menu, it will turn red, the camera will turn on, and will broadcast your video (singular video control shared among users). 
If another person press the VIDEO button, their broadcast will replace yours, but your VIDEO button and the camera will be continue to be ON. A message will be displayed below the video feed "TAP TO BROADCAST".
If you short click on the video feed, the video broadcast will switch to yours. Hide the message "TAP TO BROADCAST".
If you press on the VIDEO button, the button will turn OFF. Turn off the camera. If your video it currently showing, it will switch to the last person who was shown. If no one else is broadcasting, the video will turn off.

I tried to do so but it throws error of "video stream can not swapped".

Pls suggest a way out how to implement this using your framework.

**Comment by hasevr** [comment]
MUTE_VIDEO message defined in src/model/api/MessageTypes.ts can be used to mute videos of other participants.
When a participant receives the MUTE_VIDEO message,  onMuteVideo() at src/model/api/ConferenceSync.ts L364 will be called.
It stops the video.
You may send the message via sendMessage(type:string, value:any, to?: string)  in src/model/api/Conference.ts .

Remote video will be in props.stores.participants.remote(id).tracks.avatarStream has the video stream.
So, you will find a video stream from all remote participants in your use case.

**Comment by mumtazalam86** [comment]
Thanks for the suggestion.
But another use case is
- When a participant clicks on "Video Icon" then I want to show its video in a singular video control to itself not for the other participants and kept that "video icon" to enable all the time until the participant clicks on to close its video. 
- When the participant video is showing to its own end in a video control and the participant clicks on the video control (where video is) only then its video starts sharing to other users. But do not close the other participants videos. ( Like all user can see their video only until any other use clicks on the video to start sharing.
- If the user stops its sharing then all the users can video their video only.

Is it possible in the current working model scenario. Pls suggest.

**Comment by hasevr** [comment]
For a video preview, please set the local video stream in the local Jitsi track to a video element, then the user can see one's own video.
To share it with others, the Jitsi track must be added to the conference. The "video icon" at the bottom menu does both at once.

**Comment by mumtazalam86** [comment]
What is the different in local jitsi track and conference jitsi track and if I use the MUTE_VIDEO message from sendMessage(type:string, value:any, to?: string)  will it close the local jitsi stream or just close the conference jiitsi track.

**Comment by mumtazalam86** [comment]
Or in a simple way I need to separate the bottom main menu "Video Icon" actions. 
- On click of "video icon" just show the local track to a video element (local video display all the time"
- On click on video element to share that local video among users if click again (or another remote user start sharing its video) then remove from the sharing and again start showing the local video track.

**Comment by mumtazalam86** [comment]
Thanks for the reply
