### ISSUE TITLE
Issue getting values

### ISSUE THREAD

**Issue by mumtazalam86** [BinauralMeet/binaural-meet#113]
I am getting issue in reading the Observer object values.
As per the current script I have defined an object that contains the image and its description to RoomInfo class and update the value using connection class with "setRoomProp()". It update the value of the assign object. But when try to read the value of "roomProps" with "get("paramObjname") it given the previous default value but in the exact props it has the updated value. Can you let me know how to get the exact value or let me know if I am doing it wrong here.
I have attached the image of the correct output not not able to read the values which are in "data_" param. ("roomDetails" and its "value_"
Pls suggest.
<img width="374" alt="image" src="https://user-images.githubusercontent.com/63285304/155143396-7f370da6-e39c-4132-8ee4-f6bec754e918.png">

**Comment by hasevr** [comment]
I don't understand what is wrong. Can you share your code ?

**Comment by mumtazalam86** [comment]
No worries. I have changed the functionality to achieve this. Thanks
