### ISSUE TITLE
Video stream status issue

### ISSUE THREAD

**Issue by mumtazalam86** [BinauralMeet/binaural-meet#114]
I am trying to handle the video stream of users based on some activity. This is the issue I am getting while doing so
- When a remote user starts its stream then I receive the mediastream from "tracks.avatarStream"
- But sometimes its returns "undefined" and also "showVideo" as "false" even though the remote user is still in stream process. And after few seconds its gets the mediastream again and so on.

Why this is happening? Is there any restriction on the server side?
Or
Suggest a way out so that I can track whether the user is in streaming mode so that If the user stream return undefined in the middle of streaming process then I am show some message based in it. Like if user closed its video and no streaming then "Stream off" or if user is streaming and getting mediastream data as undefined then "Reconnecting" something like that.

**Comment by mumtazalam86** [comment]
Any suggestion on this?

**Comment by hasevr** [comment]
It depends on the number of videos.  If it is large like more than 20, only videos near the user are sent. This is based on the request from the user. The user sends an original message. Please search "setPerceptibles".

If the number of the vides are small like two or three, it will be the problem of bandwidth. Please check the internet connection and estimated bandwidth.

**Comment by mumtazalam86** [comment]
I am using 3 - 4 users and the bandwidth is good enough. But while one the remote user is broadcasting its video then it shows its stream but middle of the stream it return 'undefined' and showVideo returns 'false'. Also in the meantime I will check 'setPerceptibles' for this.

Also I want to play a tick sound and being share to all the users. So can you let me know how to calculate or the function name that plays the audio coming from left or right in the 'headphone'.

Pls suggest.

Thanks

**Comment by mumtazalam86** [comment]
I am using 3 - 4 users and the bandwidth is good enough. But while one the remote user is broadcasting its video then it shows its stream but middle of the stream it return 'undefined' and showVideo returns 'false'. Also in the meantime I will check 'setPerceptibles' for this. 
It is need just because to show some message while the stream return back if the remote user is in streaming mode.

Pls suggest.

**Comment by hasevr** [comment]
For the video, there can be two possiblilities. 
1. The video's frame rate is too low and the browser treats the stream as stopped between frames.
2. Jitsi meets bugs or problems on the server-side. Sometimes it fails to notify the addition of remote track. But it seems to occur only when there are too many tracks and the server is busy.
setPerceptible must include the participant id for the video or audio. So please check it.

For the sound control, please see /src/model/audio/
ConnectedManager.onRemotesChange manage remote audios.
src/models/trafficControl also work to determin perceptible audios and videos.

**Comment by mumtazalam86** [comment]
Okay will check and thanks for the suggestions.
