### ISSUE TITLE
binaural-meet not working

### ISSUE THREAD

**Issue by mumtazalam86** [BinauralMeet/binaural-meet#116]
Hi
I am using your framework that is using Jitsi but now its not working. Showing BMRelayServer handshake issue. Can you let me know how I can get the previous BMRelayServer and how to configure locally for the working on meet. As getting latest source and making the changes are quite time consuming. Pls suggest a quick turn around with the previous BMRelayServer.

Thanks

**Comment by hasevr** [comment]
I keep the old client at https://titech.binaural.me/ and it seems working. Please check the client side or compare with the 2022 June 3rd of the master branch.

**Comment by mumtazalam86** [comment]
Thanks for the quick turn around.
