### ISSUE TITLE
Overcome CORS for iframe of shared content

### ISSUE THREAD

**Issue by hasevr** [BinauralMeet/binaural-meet#19]
Google Docs are OK. Google calendar, Scrapbox need a header modification.

**Comment by hasevr** [comment]
https://stackoverflow.com/questions/15005500/loading-cross-domain-endpoint-with-ajax/17299796
may be a help to solve.

**Comment by hasevr** [comment]
I found hand made proxy using CURL will solve "X-Frame-Options SAMEORIGIN" problem. 
However, such proxy can not solve OAuth2.
What I tried:
.htaccess
>     RewriteEngine on
>     RewriteRule   ^(.*)$  proxy/curltest.php?$1	[L]
and the curltest.php call CURL to get header and body from the server.

It works for scrapbox.io but login was not possible.

**Comment by Elyx0** [comment]
I was fixing the same issues 2 months ago. What I can recommend as additional apps are:

Whiteboard: Iframe https://witeboard.com/
Text Editor: Iframe a https://etherpad.org/ some are public, or host your own.

There is no easy solution for https CORS that are cost effective.

**Comment by hasevr** [comment]
For the moment, use sites which allow to embed them.
Finally, need to use application rather than browser.
