### ISSUE TITLE
UI Presentation of Shared Contents

### ISSUE THREAD

**Issue by VirgiliaBeatrice** [BinauralMeet/binaural-meet#21]
Currently, the orientation of shared content will be shared globally.
When a user is trying to change his/her orientation, the local orientation of shared content will be also changed relatively.
This behavior might cause some communication difficulties with the orientation of shared content.

Considered a "poster presentation" situation, a presenter is always expected to face his/her audiences.
Keeping the orientation of shared content globally will cause whether presenter or audiences have a reversed view of shared content.
It is necessary to use a better UI presentation design of shared content to reduce those communication difficulties.

Here is a draft of the new UI design that might be useful.
![SharedContents](https://user-images.githubusercontent.com/9668444/85923121-763c0580-b8c3-11ea-9086-da3db3592606.png)

Using an abstract icon to represent shared content in the map view.
The actual content will be shown in a floating frame, which could be pinned and dragged by the user.
Those actual contents will always keep the same orientation that is easy to read for users.

This idea is just a draft concept that needs to be discussed.
Looking forward to a further discussion.

**Comment by zlguo1996** [comment]
The following image describes some core class (MapObject, ConfigurationDialog, PinBoard) for implementation:
![Share](https://user-images.githubusercontent.com/17405914/85923588-47c02980-b8c7-11ea-85c0-047842d96f81.png)

**Comment by hasevr** [comment]
I don't want to make things too complex.
May be, rotation of shared content is not needed. 
In poster presentation, presenter can direct downward, and audiences direct upward. 
If the presenter uses third person's view or accept upside down poster, the problem will solved. I think this is enough.
On the other hand, people need to point some part of the poster, currently by face is the only one method.
I think we need to share mouse cursor, in addition to face, like miro.

**Comment by zlguo1996** [comment]
- The most vital problem we meet in `current solution` is the performance. When I share two word docs in the map, the rotation operation on Map have lag.
- The problem of not rotating shared content in `first person view` is related to share mouse position. The mouse position on shared content is not same across different participants.
- The problem of not rotating shared content in `third person view` is related to stereo sound. The sound would be strange because the coordinate in sound and map is different.

**Comment by hasevr** [comment]
Now third person view is used.
