### ISSUE TITLE
Move dependency of lib-jitsi-meet

### ISSUE THREAD

**Issue by zlguo1996** [BinauralMeet/binaural-meet#6]
## Tasks
- Move dependency of lib-jitsi-meet from git submodule to npm package.json file.
- Create another repository for @types/lib-jitsi-meet, and use it in npm package.json file.

## Motivation
Use npm link is a bit complex. If move all dependencies into package.json, one command `yarn install` is enough to init the whole development enviroment.

**Comment by hasevr** [comment]
This is not good. We need to modify this lib frequetly.
