### ISSUE TITLE
Multiple screen support

### ISSUE THREAD

**Issue by zlguo1996** [BinauralMeet/binaural-meet#8]
## Motivation
Make use of multiple screen would help a lot in demonstrating the information of our web app.
## Proposal
Enabling multiple tabs for showing different aspect of contents for single user in a specific conference. What's more, those tabs could be used cross devices, which enables users to make use of their pads and smart phone for online conference.
## Example
In Jitsi-party, we could use another screen to show the videos pinged by user. Then user could use master tab to controll the map, and slave screen to show the video contents (like screen share and speaker's video).
## Approach
For the upper example, we could use WebRTC protocal to realize it. Given a conference name and user id, slave tab would tries to establish WebRTC connection with master tab. To verify the identitiy of slave tab, user would have to enter the verity code shown on master tab.
After establishment of connection, user could choose to ping several videos in master tab. Those video stream would be forwarded to slave tab from master tab using worker. Note that audio would not be forwarded, but volume could be controlled by slave tab through WebRTC connection.

**Comment by zlguo1996** [comment]
![Example](https://user-images.githubusercontent.com/17405914/83092432-40470e00-a0d8-11ea-8fd4-4d46ca28cf85.png)

**Comment by hasevr** [comment]
Because third person view is used. This is not needed.
