### ISSUE TITLE
Find out if an avatar is inside an image object

### ISSUE THREAD

**Issue by thitsa** [BinauralMeet/binaural-meet#96]
We're extending the image object in BM to have properties that effect the auditory effect of an avatar that is inside the bounds of the image. For example, the image is a conference table, and everyone at the table (i.e. inside the bounds of the image) can hear each other with equal volume, but not others that are not at the table (i.e. outside the bounds of the image).

To this end, we would like a method at the MapObject level that can return the MapObject that is immediately beneath an avatar.
e.g.  avatar.getObjBeneath()

This method needs to be aware of resized and layered images.

**Comment by hasevr** [comment]
The MapObject has pose (position (x,y) and rotation (degree). So, the actual shape is a rotated rectangle and a participant has a position. So, distance or in-out judgement can be written by JS.
For curring, we already have a utility to judge in or out. But this is not for rotated rectangles but AABB based tests.
So, need to write code for in-out check or distance calculation.

**Comment by thitsa** [comment]
This is no longer necessary due to the Meeting Space feature.

**Comment by mumtazalam86** [comment]
I am getting this error in the latest source
"TypeScript error in D:/Work/binaural-meet/src/components/leftBar/StatusDialog.tsx(96,56):
Property 'connectionQuality' does not exist on type 'JitsiConference'.  TS2339"

Can you help me what could be the reason and how to resolve this.
