### ISSUE TITLE
Audio meeting space is not working as expected

### ISSUE THREAD

**Issue by thitsa** [BinauralMeet/binaural-meet#99]
<img width="600" alt="PastedGraphic-2" src="https://user-images.githubusercontent.com/425455/139700589-fcaac163-c6cf-40c6-8077-25e99d813abe.png">

I have 2 audio meeting spaces A and B. Currently, avatars in A can hear those in B, and vice versa. This is not what I expect.

- 2 different audio meeting spaces should not be able to hear each other
- all avatars in the same audio space should be able to hear each other at the same volume (ignoring proximity)

**Comment by hasevr** [comment]
I've fixed it in commit ad73723ed473b8be04f5dce70672a807f38ff924.
Is there still the problem ?

**Comment by thitsa** [comment]
What works:
- Avatars in the Meeting Space can hear each other and proximity is ignored

What doesn't work:
- Avatars in different Meeting Spaces should NOT be able to hear each other, even if they are in close proximity. Sound should not enter or leave a Meeting Space.

**Comment by hasevr** [comment]
Please confirm the type of the meeting space.
There is "Sound proof room" which works  as you expect.
Please click dotted square icon.

**Comment by thitsa** [comment]
That works! I didn't realize the "Sound Proof Room" option. Thanks!
